### ISSUE TITLE
Using redis-pusher with Nodejs

### ISSUE THREAD

**Issue by Rohaan-Ishfaq** [jweyrich/redis-pusher#3]
Can you please give me some pointers of how can I use your pusher with Nodejs app after including it as an npm package?

**Comment by jweyrich** [comment]
Currently you shouldn't do it. As stated in the description, redis-pusher is an application on its own, not a library, at least currently. It should work out of the box to deliver your push notifications, but if you find any peculiarities in your scenario, you may change the code to fit your needs. If you think your changes may be useful to others as well, please, could consider sending a pull request so I can take a look.
